#include "GameCore.h"

void GameRegisterClasses()
{
	REGISTER_TYPECLASS(Player);
	REGISTER_TYPECLASS(Enemy);
	REGISTER_TYPECLASS(BombEnemy);
	REGISTER_TYPECLASS(GameOver);
	REGISTER_TYPECLASS(Menu);
	REGISTER_TYPECLASS(MainMenu);
	REGISTER_TYPECLASS(PauseMenu);
	REGISTER_TYPECLASS(Cursor);
	REGISTER_TYPECLASS(Spawner);
	REGISTER_TYPECLASS(HUD);
	REGISTER_TYPECLASS(Item);
	REGISTER_TYPECLASS(SpeedBoostItem);
	REGISTER_TYPECLASS(FireRateItem);
	REGISTER_TYPECLASS(ExtraLifeItem);
	REGISTER_TYPECLASS(Projectile);
}